fix: try using npm to solve tarball collision error
ERROR PackageManagerError: Tarball collision in the offline mirror: string-width-4.2.3.tgz (2x)
Error: PackageManagerError: Tarball collision in the offline mirror: string-width-4.2.3.tgz (2x)
  The cause of the failure could be:
  - something is broken in hermeto
  - something is wrong with your repository
  - communication with an external service failed (please try again)
  The output of the failing command should provide more details, please check the logs.
step-create-trusted-artifact :-
2026/01/16 16:52:49 Skipping step because a previous step failed

this is likely because the same package is resolved from two registreies in yarn.lock

Assisted-by: Cursor